spring:
  jpa:
    generate-ddl: false
    hibernate:
      show-sql: true
      ddl-auto: none
  http:
    encoding:
      forceResponse: true
      force: true
  data:
    rest:
      base-path: /data
n2o:
  engine:
    pageStartsWith0: true
    rest:
      url: http://localhost:7777
server:
  port: 9999
coinkeeper:
  backend:
    url: http://localhost:7777

frontend:
  url: http://localhost:9999



