spring:
  jpa:
    generate-ddl: false
    hibernate:
      show-sql: true
      ddl-auto: none
  http:
    encoding:
      forceResponse: true
      force: true
  data:
    rest:
      base-path: /data
n2o:
  engine:
    pageStartsWith0: true
    rest:
      url: http://localhost:8081
server:
  port: 8080






