version: '3.7'
services:
  backend:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: pass
    build:
      context: backend
      args:
        JAR_FILE: target/backend-1.0-SNAPSHOT.jar
    ports:
      - 8081:8081
    depends_on:
      - postgres
  frontend:
    environment:
      N2O_ENGINE_REST_URL: http://backend:8081
    build:
      context: frontend
      args:
        JAR_FILE: target/frontend-1.0-SNAPSHOT.jar
    ports:
      - 8080:8080
  db:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
