###
POST http://localhost:8081/media/upload/photo
Authorization: Basic user pass
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="../image.jpg"
Content-Type: image/jpeg

< ./lich.jpg
--WebAppBoundary--

###
GET http://localhost:7777/media/ru.png
Authorization: Basic user pass
Content-Type: image/jpeg


###
GET http://localhost:7777/media/lich.jpg
Authorization: Basic user pass

###
GET http://localhost:7777/media/5/images
Authorization: Basic user pass
Content-Type: image/jpeg

