
### Изображения не найдены
GET http://localhost:8888/media/77/images
X-Profile: user
Content-Type: image/jpeg

### Не поддерживаемый формат
POST http://localhost:8888/media/upload/photo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="../tmdb_5000_movies.csv"
Content-Type: text/csv

< ./tmdb_5000_movies.csv
--WebAppBoundary--

###
GET http://localhost:8888/analitics
X-Profile: user

### Расход не найден
GET http://localhost:8888/payments/112
X-Profile: user

### Кеш
GET http://localhost:8888/payments/1
X-Profile: user

### Кеш
GET http://localhost:8888/payments/category
X-Profile: user

### Нет авторизации
GET http://localhost:8888/analitics/getConsumptionGraph

