spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/baseChangelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5555/dbusers
    username: app
    password: pass
    initialization-mode: always
    platform: postgres
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      show-sql: true
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080