server:
  port: 8888
  servlet:
    session:
      cookie:
        name: UISESSION
app:
  upload:
    dir: "media/files/"
spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/baseChangelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5000/db
    username: app
    password: pass
    initialization-mode: always
    platform: postgres
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      show-sql: true
      ddl-auto: none
#  security:
#    oauth2:
#      client:
#        registration:
#          custom-client:
#            client-id: client
#            client-secret: secret
#            client-name: Auth Server
#            scope: read, write
#            provider: custom-provider
#            redirect-uri: http://localhost:8082/login/oauth2/code/
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#        provider:
#          custom-provider:
#            token-uri: http://localhost:8000/auth/oauth/token
#            authorization-uri: http://localhost:8000/auth/oauth/authorize
#            user-info-uri: http://localhost:8000/auth/user/me
#            user-name-attribute: name






